name: Pre-commit Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23.2" # Adjust to your Node.js version
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Run Prettier
        run: yarn prettier --check .

      - name: Run ESLint
        run: yarn eslint .

      - name: Run Tests
        run: yarn jest
