name: Run Pre-commit Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23.2"

      - name: Install dependencies
        run: |
          yarn install

      - name: Run Prettier
        run: |
          yarn prettier --check .

      - name: Run ESLint
        run: |
          yarn eslint --ext .js,.jsx,.ts,.tsx .

      - name: Run tests
        run: |
          yarn test
